version: '3'

services:
  bitcoin-node:
    build:
      context: BtcCore
      dockerfile: dockerfile
    ports:
      - "18330:18332"
    volumes:
      - ../data/bitcoin:/data
  guardian-angel:
    build:
      dockerfile: dockerfile
    volumes:
      - ./config:/config
    ports:
      - "5000:5000"
  palas:
    image: ghcr.io/txpipe/dolos:latest
    ports:
      - "5001:5001"
    volumes:
      -  ./daemon.toml:/etc/dolos/daemon.toml
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db
