version: '3'

services:
  bitcoin:
    build:
      context: BtcCore
      dockerfile: dockerfile
    volumes:
      - ../volume/data/bitcoin:/data
  guardian-angel:
    build:
      dockerfile: dockerfile
    volumes:
      - ./config:/app/config
    ports:
      - "5000:5000"
    restart: always
  dolos:
    image: ghcr.io/txpipe/dolos:latest
    volumes:
      -  ./dolos/preview/preview.toml:/etc/dolos/daemon.toml
      -  ./dolos/preview/genesis:/etc/dolos/genesis 
      - ../dolos/data:/data
    entrypoint: sh -c " dolos daemon "  
  mongo:
    image: mongo
    restart: always
    ports:
      -  "0.0.0.0:27017:27017"
    volumes:
      - ./data/mongo:/data/db
