version: '3'

services:
  bitcoin:
    build:
      context: BtcCore
      dockerfile: dockerfile
    volumes:
      - ../data/bitcoin:/data
  guardian-angel:
    build:
      dockerfile: dockerfile
      context: .
    volumes:
      - ./config:/app/config
    ports:
      - "3000:3000"
      - "3030:3030"
    restart: always
    depends_on:
      - mongo 
      - dolos
      - bitcoin
  dolos:
    image: ghcr.io/txpipe/dolos:latest
    volumes:
      -  ./config/dolos.toml:/etc/dolos/daemon.toml
      -  ./dolos/preprod/genesis:/etc/dolos/genesis 
      - ../data/dolos:/data
    entrypoint: sh -c " dolos daemon "  
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:50051 || exit 1"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  mongo:
    image: mongo
    restart: always
    ports:
      -  "127.0.0.1:27017:27017"
    volumes:
      - ../data/mongo:/data/db
