services:
  bitcoin:
    build:
      context: BtcCore
      dockerfile: dockerfile
    volumes:
      - ../data/bitcoin:/data
    networks:
      - backend
      - frontend
    healthcheck:
      test: ["CMD", "bitcoin-cli", "getblockchaininfo"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  guardian-angel:
    build:
      dockerfile: dockerfile
      context: .
    volumes:
      - ./config:/app/config
    ports:
      - "3000:3000"
      - "3030:3030"
    restart: always
    depends_on:
      - mongo
      - dolos
      - bitcoin
    user: "1000:1000"
    networks:
      - backend
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  dolos:
    image: ghcr.io/txpipe/dolos:latest
    volumes:
      -  ./config/dolos.toml:/etc/dolos/daemon.toml
      -  ./dolos/preprod/genesis:/etc/dolos/genesis
      - ../data/dolos:/data
    entrypoint: sh -c " dolos daemon "
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:50051 || exit 1"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - backend
      - frontend
  mongo:
    image: mongo
    restart: always
    ports:
      -  "127.0.0.1:27017:27017"
    volumes:
      - ../data/mongo:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand(\"ping\").ok'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - backend


networks:
  backend:
    internal: true
  frontend:
    driver: bridge
