version: '3'

services:
  bitcoin:
    build:
      context: BtcCore
      dockerfile: dockerfile
    volumes:
      - ../volume/data/bitcoin:/data
  guardian-angel:
    build:
      dockerfile: dockerfile
      context: .
    volumes:
      - ./config:/app/config
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mongo 
      - dolos
      - bitcoin
  dolos:
    image: ghcr.io/txpipe/dolos:latest
    volumes:
      -  ./dolos/preview/preview.toml:/etc/dolos/daemon.toml
      -  ./dolos/preview/genesis:/etc/dolos/genesis 
      - ../dolos/data:/data
    entrypoint: sh -c " dolos daemon "  
    healthcheck:
      test: curl --fail http://localhost:50051 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  mongo:
    image: mongo
    restart: always
    ports:
      -  "127.0.0.1:27017:27017"
    volumes:
      - ./data/mongo:/data/db
