version: '3'

services:
  bitcoin-node:
    build:
      context: BtcCore
      dockerfile: dockerfile
    ports:
      - "18330:18332"
    volumes:
      - ../data/bitcoin:/data
  guardian-angel:
    build:
      dockerfile: dockerfile
    volumes:
      - ./config:/app/config
    ports:
      - "5000:5000"

  dolos:
    image: ghcr.io/txpipe/dolos:latest
    ports:
      - "50051:50051"
    volumes:
      -  ./dolos/preview/preview.toml:/etc/dolos/daemon.toml
      -  ./dolos/preview/genesis:/etc/dolos/genesis 
      - ../dolos/data:/data
    entrypoint: sh -c "dolos --config /etc/dolos/daemon.toml bootstrap  && dolos --config /etc/dolos/daemon.toml daemon "  
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
