FROM ubuntu:latest

ENV COIN_VERSION="27.0"
ENV TARBALL_NAME="bitcoin-${COIN_VERSION}"
ENV BINARY_URL="https://bitcoincore.org/bin/bitcoin-core-${COIN_VERSION}/${TARBALL_NAME}-x86_64-linux-gnu.tar.gz"
ENV COIN_TMP="/var/tmp/"
ENV COIN_CONF_FILE="/etc/btc/config.conf"

RUN apt update && apt upgrade -y && apt install curl -y

RUN curl -L "${BINARY_URL}" -o "${COIN_TMP}/${TARBALL_NAME}-x86_64-linux-gnu.tar.gz" \
    && tar -C "${COIN_TMP}" -xzvf "${COIN_TMP}/${TARBALL_NAME}-x86_64-linux-gnu.tar.gz"

COPY ./config.conf  /root/.bitcoin/bitcoin.conf

RUN mv ${COIN_TMP}/${TARBALL_NAME}/bin/* /usr/bin/ \
    && mv ${COIN_TMP}/${TARBALL_NAME}/include/* /usr/include/ \
    && mv ${COIN_TMP}/${TARBALL_NAME}/lib/* /usr/lib/ \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*  \
    && mkdir /data

EXPOSE 18332

CMD ["bitcoind"]
